name: Auto Tag from Release Branch

on:
  push:
    branches:
      - main
      - 'release/v*'

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check and create tag from branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Checking branch name..."
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ release/v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="v${BASH_REMATCH[1]}"
            echo "✅ Detected release version: $VERSION"

            git config user.name "github-actions"
            git config user.email "actions@github.com"

            git tag "$VERSION"
            git push origin "$VERSION"
          else
            echo "❌ Not a release branch. Skipping tag."
          fi
